builds:
  - 
    main: ./main.go
    binary: exconv
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ignore:
      - goos: windows
        goarch: arm 
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: 386  
    ldflags:
      - -s -w -X diagram-converter/cmd.version={{.Version}} -X diagram-converter/cmd.commit={{.Commit}}
archives:
  -
    replacements:
      darwin: macOS
      386: i386
    format_overrides:
    - goos: windows
      format: zip

brews:
  -
    name: excalidraw-converter
    tap:
      # Homebrew Tap Repository
      owner: sindrel
      name: homebrew-tap

    url_template: "https://github.com/sindrel/excalidraw-converter/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    folder: Formula

    # Your app's homepage.
    homepage: "https://github.com/sindrel/excalidraw-converter"

    # Template of your app's description.
    description: "A command line tool for porting Excalidraw diagrams to Gliffy."
    #caveats: "To convert an Excalidraw diagram to a Gliffy diagram, run: 'exconv gliffy <input-file> <output-file>'"

    # SPDX identifier of your app's license.
    license: "MIT"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: auto

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/exconv version"
    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "exconv"
